"""Pydantic models for the Cloud Runner backend API."""

from pydantic import BaseModel
from typing import Optional


class Source(BaseModel):
    """A citation source retrieved from the Knowledge Base (RAG grounding)."""

    title: str
    url: Optional[str] = None
    snippet: str


class QuizRequest(BaseModel):
    """Request to generate a 4-choice quiz question for a service collected in the runner game."""

    service_id: str
    service_name: str
    category: str
    difficulty: Optional[str] = None  # Beginner | Intermediate | Advanced | Expert, scales with in-run score


class QuizResponse(BaseModel):
    """A generated multiple-choice quiz question."""

    question: str
    choices: list[str]
    correct_index: int
    fact: str  # shown as feedback regardless of correctness


class ServiceNotes(BaseModel):
    """The incremental notes the player has actually unlocked for one
    service this run, in the order they were taught (most basic first,
    most recently taught last). Each entry was generated by /orb-note when
    the player collected that service's notes orb — one NEW, deeper note
    per collection, building from zero. Used to ground lane-quiz generation
    so questions never test beyond what the player has actually been shown
    in-game.
    """

    service_name: str
    category: str
    notes: list[str] = []


class LaneQuizRequest(BaseModel):
    """Request for a 3-choice quiz question used by the in-run lane-gate mechanic."""

    service_id: str
    service_name: str
    category: str
    difficulty: Optional[str] = None  # Beginner | Intermediate | Advanced | Expert

    # Whether the player collected this exact service's notes orb this run.
    # When True, target_notes MUST be populated and the question is grounded
    # strictly in it. When False, the question must stay at category level -
    # it cannot test anything specific to this service that the player was
    # never shown.
    has_notes: bool = False
    target_notes: Optional[ServiceNotes] = None

    # Notes for OTHER services the player has already unlocked this run.
    # The question may reference/compare against these (quizzes can "build
    # off old orbs"), but still may not exceed what's stated in them.
    unlocked_notes: Optional[list[ServiceNotes]] = None


class OrbNoteRequest(BaseModel):
    """Request for the next incremental teaching note unlocked by collecting
    a service's notes orb. `prior_notes` is everything already taught to the
    player about this service this run (empty on the first collection) -
    the new note must build on top of these from zero, without repeating them.
    """

    service_id: str
    service_name: str
    category: str
    prior_notes: list[str] = []


class OrbNoteResponse(BaseModel):
    """One new, self-contained teaching note - shown as the orb-collection
    toast and made available in the in-run quiz notes panel.
    """

    note: str


class LaneQuizResponse(BaseModel):
    """A generated 3-choice quiz question, one choice per lane (left/center/right)."""

    question: str
    choices: list[str]  # exactly 3, index 0=left, 1=center, 2=right
    correct_index: int  # 0, 1, or 2
    fact: str


class AskQuestionRequest(BaseModel):
    """A free-text follow-up question scoped to a specific service, asked from the runner game."""

    service_id: str
    service_name: str
    category: str
    question: str
    conversation_history: Optional[list] = None


class AskQuestionResponse(BaseModel):
    """Answer to a free-text follow-up question."""

    answer: str
    sources: list[Source] = []
